### ISSUE TITLE
firelensにおけるparsers.confのファイル名

### ISSUE THREAD

**Issue by seeds-haraguchi** [uma-arai/sbcntr-resources#5]
https://github.com/uma-arai/sbcntr-resources/blob/main/firelens/parsers.conf

https://github.com/uma-arai/sbcntr-resources/blob/main/firelens/Dockerfile#L4
を見る形ですとファイル名は myparsers.conf が正ではないでしょうか？

**Comment by horsewin** [comment]
起票ありがとうございます＆反応が遅れてしまいすいません。
内容確認し、修正が必要な際は出版社へもフィードバックしておきます！

**Comment by horsewin** [comment]
本文の修正は不要でしたので、ファイル名のみリネームしておきました。コメントいただきありがとうございます！
